name: Deploy Docs
on:
  push:
    branches: [main]

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -U pip wheel hatch
      - run: hatch run docs
