name: Release webdav4

on:
  push:
    branches:
    - main
  release:
    types:
      - released

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
            python-version: 3.7

      - name: Force version for Test PyPI uploads
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        run: |
          version=$(hatch version | awk -F+ '{print $1}' | tail -1)
          echo SETUPTOOLS_SCM_PRETEND_VERSION=$version >> $GITHUB_ENV
          echo version $version

      - run: pip install -U pip wheel hatch
      - run: hatch build
